### ISSUE TITLE
Does it support Raspberry Pi 3B+?

### ISSUE THREAD

**Issue by ZeroAurora** [FydeOS/chromium_os_for_raspberry_pi#1]
I have a Raspberry Pi 3 Model B+. Can I use this image on it?
我有一个 RPI 3B+（配置与 3B 略有不同），我能不能把这个系统用在它上面？

**Comment by yunshansimon** [comment]
I'm not sure. We only got RPI3. A few people said they got a black screen.
The OS is running on the official kernel of Raspberry. You can change the
config.txt or cmdline.txt to support new hardware.

**Comment by hellzapop** [comment]
I tried the prebuilt image with Raspberry Pi3 B+ and everything is working except for the wifi! 
I think is a driver thing for the internal wifi because i plugged a wifi usb external adapter and is working fine.
Chromium is super fast!
I just changed the hdmi settings in config.txt:
hdmi_force_hotplug=1
hdmi_group=2
hdmi_mode=85

Do you know how i can enable the internal wifi?

**Comment by yunshansimon** [comment]
RPI 3B+ wifi chip: cyw43455. linux driver: [cypress.com official driver](https://community.cypress.com/docs/DOC-14597,) you can build the kernel by yourself, or wait a while.

**Comment by hellzapop** [comment]
Thank you!
